version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: my-nginx
        ports:
            - '8000:80'
            - '9000:9000'
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html
        depends_on:
            - php
        networks:
            - my-network

    php:
        build:
            context: ./.docker
            dockerfile: Dockerfile
        container_name: my-php
        volumes:
            - ./public:/var/www/html
        networks:
            - my-network

    mysql:
        image: mysql:5.7
        container_name: my-mysql
        environment:
            MYSQL_ROOT_PASSWORD: tt12tt34
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: BE31pZuCAO5a
        ports:
            - '8006:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my-phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - my-network

volumes:
    mysql_data:

networks:
    my-network:
